name: Documentation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-dev python3-venv build-essential meson ninja-build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PYTHONUNBUFFERED: 1

      - name: Parse Code Comments with Sphinx
        run: |
          cd docs/sphinx
          make html

      - name: Transform Markdown
        run: |
          python transform_docs.py --input docs/_build/html --output docs/markdown
        env:
          PYTHONUNBUFFERED: 1

      - name: Translate Documentation
        run: |
          python translate_docs.py --source docs/markdown --target docs/translations
        env:
          PYTHONUNBUFFERED: 1

      - name: Structure Documentation with MkDocs
        run: |
          mkdocs build --site-dir docs/site
        env:
          PYTHONUNBUFFERED: 1

      - name: Validate Documentation with Great Expectations
        run: |
          great_expectations checkpoint run documentation_validation_checkpoint
        env:
          PYTHONUNBUFFERED: 1

      - name: Save Validation Report
        if: always()
        run: |
          if [ -d "great_expectations/uncommitted/data_docs/" ] && [ "$(ls -A great_expectations/uncommitted/data_docs/)" ]; then
            echo "Directory exists and is not empty; uploading artifact."
            mkdir -p artifacts
            cp -r great_expectations/uncommitted/data_docs/ artifacts/
          else
            echo "Directory does not exist or is empty; skipping artifact upload."
          fi

      - name: Upload Validation Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: validation-report
          path: artifacts

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/site