name: Docs CI Workflow  # More concise workflow name

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12'] # You are explicitly using 3.12, so let's keep it fixed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            build-essential \
            meson \
            ninja-build \
            gfortran \
            libopenblas-dev \
            liblapack-dev \
            pkg-config \
            libffi-dev

      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # Enable pip caching - SPEED BOOST!

      - name: Install Dependencies
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python -m pip install --upgrade pip setuptools wheel # Using default python (3.12 from setup-python)
          pip install -r requirements.txt # Using default pip (associated with 3.12)

      - name: Run Code Style Fixer (autopep8)
        run: |
          find . -name "*.py" -print0 | while IFS= read -r -d $'\0' file; do
            echo "Formatting: $file"
            python style_fixer.py "$file"
          done

      - name: Parse Code Comments with Sphinx
        run: |
          cd docs/sphinx
          make html

      - name: Transform Markdown
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python transform_docs.py --input docs/_build/html --output docs/markdown

      - name: Translate Documentation
        env:
          PYTHONUNBUFFERED: 1
        run: |
          python translate_docs.py --source docs/markdown --target docs/translations

      - name: Structure Documentation with MkDocs
        env:
          PYTHONUNBUFFERED: 1
        run: |
          mkdocs build --site-dir docs/site

      - name: Validate Documentation with Great Expectations
        env:
          PYTHONUNBUFFERED: 1
        run: |
          great_expectations checkpoint run documentation_validation_checkpoint

      - name: Prepare Validation Artifacts
        if: always()
        run: |
          if [ -d "great_expectations/uncommitted/data_docs/" ] && [ "$(ls -A great_expectations/uncommitted/data_docs/)" ]; then
            echo "Validation artifacts found. Copying to an artifacts folder..."
            mkdir -p artifacts
            cp -r great_expectations/uncommitted/data_docs/* artifacts/
          else
            echo "No validation artifacts found or directory is empty."
          fi

      - name: Upload Validation Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-report
          path: artifacts

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/site